version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  student-frontend:
    build:
      context: ./student-frontend
      dockerfile: Dockerfile
    ports:
      - "5174:80"
    restart: unless-stopped
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    restart: unless-stopped
    depends_on:
      - backend
