apiVersion: v1
kind: Secret
metadata:
  name: rms-secrets
type: Opaque
stringData:
  # In a real production environment, these would be encrypted using a tool like SOPS or AWS Secrets Manager.
  # For this project, we define them directly for simplicity.
  DATABASE_URL: "postgresql://neondb_owner:npg_b84LtJluGHYx@ep-late-shadow-b3vnchri-pooler.c-4.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&pgbouncer=true"
  JWT_SECRET: "supersecret_ruhuna_key"
  NODE_ENV: "production"
